Class BPLIteration.Msg.AnswerResponse Extends (Ens.Response, Answer)
{

Storage Default
{
<Data name="AnswerResponseDefaultData">
<Subscript>"AnswerResponse"</Subscript>
<Value name="1">
<Value>Answer</Value>
</Value>
<Value name="2">
<Value>Subject</Value>
</Value>
<Value name="3">
<Value>Choice</Value>
</Value>
</Data>
<DefaultData>AnswerResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
