Class BPLIteration.Msg.FileRequest Extends (Ens.Request, Answer)
{

Storage Default
{
<Data name="FileRequestDefaultData">
<Subscript>"FileRequest"</Subscript>
<Value name="1">
<Value>Answer</Value>
</Value>
<Value name="2">
<Value>Subject</Value>
</Value>
<Value name="3">
<Value>Choice</Value>
</Value>
</Data>
<DefaultData>FileRequestDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
