Class BPLIteration.Msg.SingleQuestionRequest Extends (Ens.Request, Question)
{

Storage Default
{
<Data name="SingleQuestionRequestDefaultData">
<Subscript>"SingleQuestionRequest"</Subscript>
<Value name="1">
<Value>Question</Value>
</Value>
<Value name="2">
<Value>Subject</Value>
</Value>
<Value name="3">
<Value>Options</Value>
</Value>
</Data>
<DefaultData>SingleQuestionRequestDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
